# Generated by Django 3.2 on 2023-02-08 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainee',
            name='phone_number',
        ),
        migrations.CreateModel(
            name='TraineePhoneNumber',
            fields=[
                ('phonenumber_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.phonenumber')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_number', to='account.trainee')),
            ],
            bases=('account.phonenumber',),
        ),
    ]
