# Generated by Django 3.2 on 2023-02-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20230208_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymowner',
            name='license_number',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
