# Generated by Django 3.2 on 2023-07-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_baseuser_reset_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='verify_code',
            field=models.IntegerField(blank=True, max_length=6, null=True),
        ),
    ]
