# Generated by Django 3.2 on 2023-07-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_baseuser_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='baseuser',
            name='phone_number',
            field=models.CharField(blank=True, default=None, max_length=11, null=True, unique=True),
        ),
    ]
