# Generated by Django 3.2 on 2023-07-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='gym',
            name='license_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='gym/license/'),
        ),
    ]
