# Generated by Django 3.2 on 2023-07-09 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20230709_2232'),
        ('gym', '0004_auto_20230708_1926'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Invitation',
            new_name='TrainerInvitation',
        ),
    ]
