# Generated by Django 3.2 on 2023-07-09 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20230709_2232'),
        ('gym', '0005_rename_invitation_trainerinvitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraineeInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.plan')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.trainee')),
            ],
            options={
                'unique_together': {('plan', 'trainee')},
            },
        ),
    ]
